version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t simpleapi:latest . 
      - echo Hello worlds
      - docker tag simpleapi:latest public.ecr.aws/y4a9h3w8/codebuildtasks   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/y4a9h3w8/codebuildtasks:latest
